/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina - www.xs-labs.com
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

/*!
 * @file        ...
 * @copyright   (c) 2012 - Jean-David Gadina - www.xs-labs.com
 * @abstract    ...
 */

#import "DMImageScrollView.h"

@implementation DMImageScrollView

- ( id )initWithFrame: ( CGRect )frame
{
    if( ( self = [ super initWithFrame: frame ] ) )
    {
        self.showsVerticalScrollIndicator   = NO;
        self.showsHorizontalScrollIndicator = NO;
        self.bouncesZoom                    = YES;
        self.decelerationRate               = UIScrollViewDecelerationRateFast;
        self.delegate                       = self;
        self.backgroundColor                = [ UIColor colorWithPatternImage: [ UIImage imageNamed: @"Grid.png" ] ];
    }
    
    return self;
}

- ( void )dealloc
{
    [ _imageView release ];
    [ _image     release ];
    
    [ super dealloc ];
}

- ( void )layoutSubviews 
{
    CGSize boundsSize;
    CGRect frameToCenter;
    
    [ super layoutSubviews ];
    
    boundsSize    = self.bounds.size;
    frameToCenter = _imageView.frame;
    
    if( frameToCenter.size.width < boundsSize.width )
    {
        frameToCenter.origin.x = ( boundsSize.width - frameToCenter.size.width ) / ( CGFloat )2;
    }
    else
    {
        frameToCenter.origin.x = ( CGFloat )0;
    }
    
    if( frameToCenter.size.height < boundsSize.height )
    {
        frameToCenter.origin.y = ( boundsSize.height - frameToCenter.size.height ) / ( CGFloat )2;
    }
    else
    {
        frameToCenter.origin.y = ( CGFloat )0;
    }
    
    _imageView.frame = frameToCenter;
}

- ( UIView * )viewForZoomingInScrollView: ( UIScrollView * )scrollView
{
    ( void )scrollView;
    
    return _imageView;
}

- ( UIImage * )image
{
    @synchronized( self )
    {
        return _image;
    }
}

- ( void) setImage: ( UIImage * )image
{
    @synchronized( self )
    {
        [ _imageView removeFromSuperview ];
        
        [ _imageView release ];
        [ _image     release ];
        
        _imageView = nil;
        _image     = nil;
        
        if( image == nil )
        {
            return;
        }
        
        _image         = [ image retain ];
        _imageView     = [ [ UIImageView alloc ] initWithImage: _image ];
        
        self.zoomScale   = ( CGFloat )1;
        self.contentSize = [ _image size ];
        
        [ self addSubview: _imageView ];
        [ self setMaxMinZoomScalesForCurrentBounds ];
        
        self.zoomScale = self.minimumZoomScale;
    }
}

- ( void )setMaxMinZoomScalesForCurrentBounds
{
    CGSize  boundsSize;
    CGSize  imageSize;
    CGFloat xScale;
    CGFloat yScale;
    CGFloat minScale;
    CGFloat maxScale;
    
    boundsSize = self.bounds.size;
    imageSize  = _imageView.bounds.size;
    xScale     = boundsSize.width / imageSize.width;
    yScale     = boundsSize.height / imageSize.height;
    minScale   = MIN( xScale, yScale );
    maxScale   = ( CGFloat )1 / [ [ UIScreen mainScreen ] scale ];
    
    if( minScale > maxScale )
    {
        minScale = maxScale;
    }
    
    maxScale *= 5;
    
    self.maximumZoomScale = maxScale;
    self.minimumZoomScale = minScale;
}

- ( CGPoint )pointToCenterAfterRotation
{
    CGPoint boundsCenter;
    
    boundsCenter = CGPointMake
    (
        CGRectGetMidX( self.bounds ),
        CGRectGetMidY( self.bounds )
    );
    
    return [ self convertPoint: boundsCenter toView: _imageView ];
}

- ( CGFloat )scaleToRestoreAfterRotation
{
    CGFloat contentScale;
    
    contentScale = self.zoomScale;
     
    if( contentScale <= self.minimumZoomScale + FLT_EPSILON )
    {
        contentScale = ( CGFloat )0;
    }
    
    return contentScale;
}

- ( void )restoreCenterPoint: ( CGPoint )oldCenter scale: ( CGFloat )oldScale
{
    CGPoint boundsCenter;
    CGPoint offset;
    CGPoint maxOffset;
    CGPoint minOffset;
    
    self.zoomScale = MIN
    (
        self.maximumZoomScale,
        MAX( self.minimumZoomScale, oldScale )
    );
    
    boundsCenter = [ self convertPoint: oldCenter fromView: _imageView ];
    offset       = CGPointMake( boundsCenter.x - self.bounds.size.width  / ( CGFloat )2,  boundsCenter.y - self.bounds.size.height / ( CGFloat )2 );
    
    maxOffset    = CGPointMake( self.contentSize.width  - self.bounds.size.width, self.contentSize.height - self.bounds.size.height );
    minOffset    = CGPointZero;
    
    offset.x     = MAX( minOffset.x, MIN( maxOffset.x, offset.x ) );
    offset.y     = MAX( minOffset.y, MIN( maxOffset.y, offset.y ) );
    
    self.contentOffset = offset;
}

@end
