/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina - www.xs-labs.com
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

/*!
 * @file        ...
 * @copyright   (c) 2012 - Jean-David Gadina - www.xs-labs.com
 * @abstract    ...
 */

#import "DMFile.h"
#import "DMFile+Private.h"

@implementation DMFile

@synthesize isDirectory                 = _isDirectory;
@synthesize isRegularFile               = _isRegularFile;
@synthesize isSymbolicLink              = _isSymbolicLink;
@synthesize isSocket                    = _isSocket;
@synthesize isCharacterSpecial          = _isCharacterSpecial;
@synthesize isBlockSpecial              = _isBlockSpecial;
@synthesize isUnknown                   = _isUnknown;
@synthesize isImmutable                 = _isImmutable;
@synthesize isAppendOnly                = _isAppendOnly;
@synthesize isBusy                      = _isBusy;
@synthesize isImage                     = _isImage;
@synthesize isAudio                     = _isAudio;
@synthesize isVideo                     = _isVideo;
@synthesize flags                       = _flags;
@synthesize extensionIsHidden           = _extensionIsHidden;
@synthesize isReadable                  = _isReadable;
@synthesize isWriteable                 = _isWriteable;
@synthesize isExecutable                = _isExecutable;
@synthesize size                        = _size;
@synthesize referenceCount              = _referenceCount;
@synthesize deviceIdentifier            = _deviceIdentifier;
@synthesize ownerID                     = _ownerID;
@synthesize groupID                     = _groupID;
@synthesize permissions                 = _permissions;
@synthesize octalPermissions            = _octalPermissions;
@synthesize systemNumber                = _systemNumber;
@synthesize systemFileNumber            = _systemFileNumber;
@synthesize HFSCreatorCode              = _HFSCreatorCode;
@synthesize HFSTypeCode                 = _HFSTypeCode;
@synthesize numberOfSubFiles            = _numberOfSubFiles;
@synthesize path                        = _path;
@synthesize filename                    = _filename;
@synthesize displayName                 = _displayName;
@synthesize fileExtension               = _fileExtension;
@synthesize parentDirectoryPath         = _parentDirectoryPath;
@synthesize type                        = _type;
@synthesize owner                       = _owner;
@synthesize group                       = _group;
@synthesize humanReadableSize           = _humanReadableSize;
@synthesize humanReadablePermissions    = _humanReadablePermissions;
@synthesize creationDate                = _creationDate;
@synthesize modificationDate            = _modificationDate;
@synthesize icon                        = _icon;
@synthesize targetFile                  = _targetFile;

+ ( DMFile * )fileWithPath: ( NSString * )filePath
{
    DMFile * fileInfos;
    
    fileInfos = [ [ DMFile alloc ] initWithPath: filePath ];
    
    return [ fileInfos autorelease ];
}

- ( id )initWithPath: ( NSString * )filePath
{
    NSString * symLinkTarget;
    NSError  * e;
    
    if( ( self = [ super init ] ) )
    {
        _path        = [ filePath copy ];
        _fileManager = [ NSFileManager defaultManager ];
        
        if( [ _fileManager fileExistsAtPath: _path ] == NO )
        {
            [ self autorelease ];
            
            return nil;
        }
        
        e           = nil;
        _attributes = [ [ _fileManager attributesOfItemAtPath: _path error: &e ] retain ];
        
        if( _attributes == nil || e != nil )
        {
            [ self autorelease ];
            
            return nil;
        }
        
        [ self getPathInfos ];
        [ self getFileType ];
        [ self getOwnership ];
        [ self getPermissions ];
        [ self getFlags ];
        [ self getSize ];
        [ self getDates ];
        [ self getFileSystemAttributes ];
        
        if( _isDirectory == YES )
        {
            _numberOfSubFiles = [ [ _fileManager contentsOfDirectoryAtPath: _path error: NULL ] count ];
        }
        
        if( _isSymbolicLink == YES )
        {
            symLinkTarget = [ _fileManager destinationOfSymbolicLinkAtPath: _path error: NULL ];
            
            if( [ symLinkTarget characterAtIndex: 0 ] != '/' )
            {
                if( [ _parentDirectoryPath characterAtIndex: [ _parentDirectoryPath length ] - 1 ] == '/' )
                {
                    symLinkTarget = [ _parentDirectoryPath stringByAppendingString: symLinkTarget ];
                }
                else
                {
                    symLinkTarget = [ NSString stringWithFormat: @"%@/%@", _parentDirectoryPath, symLinkTarget ];
                }
            }
            
            _targetFile = [ [ DMFile alloc ] initWithPath: symLinkTarget ];
        }
        
        [ self getSubTypes ];
        [ self getIcon ];
    }
    
    return self;
}

- ( void )dealloc
{
    [ _path                     release ];
    [ _filename                 release ];
    [ _displayName              release ];
    [ _fileExtension            release ];
    [ _parentDirectoryPath      release ];
    [ _attributes               release ];
    [ _owner                    release ];
    [ _group                    release ];
    [ _humanReadablePermissions release ];
    [ _type                     release ];
    [ _humanReadableSize        release ];
    [ _creationDate             release ];
    [ _modificationDate         release ];
    [ _icon                     release ];
    [ _targetFile               release ];
    
    [ super dealloc ];
}

- ( NSString * )description
{
    return [ NSString stringWithFormat: @"%@ - %@", [ super description ], self.path ];
}

@end
