/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina - www.xs-labs.com
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

/*!
 * @header      ...
 * @copyright   (c) 2012 - Jean-David Gadina - www.xs-labs.com
 * @abstract    ...
 */

#include <sys/mount.h>

@interface DMPartition: NSObject
{
@protected
    
    uint32_t    _blockSize;
    int32_t     _ioSize;
    uint64_t    _blocks;
    uint64_t    _freeBlocks;
    uint64_t    _availableBlocks;
    uint64_t    _fileNodes;
    uint64_t    _freeFileNodes;
    fsid_t      _fileSystemID;
    uid_t       _ownerID;
    uint32_t    _type;
    uint32_t    _flags;
    uint32_t    _subType;
    NSString *  _typeName;
    NSString *  _mountPoint;
    NSString *  _mountedFS;
    
@private
    
    id __DMPartition_Reserved[ 5 ] __attribute__( ( unused ) );
}

@property( atomic, readonly ) uint32_t    blockSize;
@property( atomic, readonly ) int32_t     ioSize;
@property( atomic, readonly ) uint64_t    blocks;
@property( atomic, readonly ) uint64_t    freeBlocks;
@property( atomic, readonly ) uint64_t    availableBlocks;
@property( atomic, readonly ) uint64_t    fileNodes;
@property( atomic, readonly ) uint64_t    freeFileNodes;
@property( atomic, readonly ) fsid_t      fileSystemID;
@property( atomic, readonly ) uid_t       ownerID;
@property( atomic, readonly ) uint32_t    type;
@property( atomic, readonly ) uint32_t    flags;
@property( atomic, readonly ) uint32_t    subType;
@property( atomic, readonly ) NSString *  typeName;
@property( atomic, readonly ) NSString *  mountPoint;
@property( atomic, readonly ) NSString *  mountedFS;

+ ( NSArray * )availablePartitions;

@end
