/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina - www.xs-labs.com
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

/*!
 * @header      ...
 * @copyright   (c) 2012 - Jean-David Gadina - www.xs-labs.com
 * @abstract    ...
 */

#import "DMProcessesViewController+UITableViewDataSource.h"
#import "DMProcessesTableViewCell.h"
#import "DMProcess.h"
#import "DMGroupedTableViewCellBackgroundView.h"

@implementation DMProcessesViewController( UITableViewDataSource )

- ( NSInteger )numberOfSectionsInTableView: ( UITableView * )tableView
{
    ( void )tableView;
    
    return 1;
}

- ( NSInteger )tableView: ( UITableView * )tableView numberOfRowsInSection: ( NSInteger )section
{
    ( void )tableView;
    
    if( section == 0 )
    {
        return ( NSInteger )( _processes.count );
    }
    
    return 0;
}

- ( UITableViewCell * )tableView: ( UITableView * )tableView cellForRowAtIndexPath: ( NSIndexPath * )indexPath
{
    DMProcessesTableViewCell             * cell;
    DMProcess                            * process;
    DMGroupedTableViewCellBackgroundView * backgroundView;
    
    cell = ( DMProcessesTableViewCell * )[ tableView dequeueReusableCellWithIdentifier: DMProcessesTableViewCellID ];
    
    if( cell == nil )
    {
        cell = [ [ DMProcessesTableViewCell new ] autorelease ];
    }
    
    @try
    {
        process = [ _processes objectAtIndex: ( NSUInteger )( indexPath.row ) ];
    }
    @catch( NSException * e )
    {
        ( void )e;
        
        process = nil;
    }
    
    cell.process = process;
    
    backgroundView                       = [ [ [ DMGroupedTableViewCellBackgroundView alloc ] initWithFrame: CGRectZero ] autorelease ];
    backgroundView.backgroundViewType    = DMGroupedTableViewCellBackgroundViewTypeMiddle;
    backgroundView.fillColor             = [ UIColor colorWithPatternImage: [ UIImage imageNamed: @"RootTable-CellBackground.png" ] ];
    
    if( indexPath.row == 0 && _processes.count == 1 )
    {
        backgroundView.backgroundViewType = DMGroupedTableViewCellBackgroundViewTypeSingle;
    }
    else if( indexPath.row == 0 )
    {
        backgroundView.backgroundViewType = DMGroupedTableViewCellBackgroundViewTypeTop;
    }
    else if( ( NSUInteger )( indexPath.row ) == _processes.count - 1 )
    {
        backgroundView.backgroundViewType = DMGroupedTableViewCellBackgroundViewTypeBottom;
    }
    else
    {
        backgroundView.backgroundViewType = DMGroupedTableViewCellBackgroundViewTypeMiddle;
    }
    
    cell.backgroundView = backgroundView;
    
    return cell;
}

- ( NSString * )tableView: ( UITableView * )tableView titleForHeaderInSection: ( NSInteger )section
{
    ( void )tableView;
    
    if( section == 0 )
    {
        return NSLocalizedString( @"RunningProcesses", @"RunningProcesses" );
    }
    
    return nil;
}

@end
