/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina - www.xs-labs.com
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

/*!
 * @file        ...
 * @copyright   (c) 2012 - Jean-David Gadina - www.xs-labs.com
 * @abstract    ...
 */

#import "DMFileSystemFileListTableViewController.h"
#import "DMFileSystemFileListTableViewController+Private.h"
#import "DMFileSystemFileListTableViewController+UITableViewDelegate.h"
#import "DMFileSystemFileListTableViewController+UITableViewDataSource.h"
#import "DMFile.h"
#import "DMPreferences.h"

@implementation DMFileSystemFileListTableViewController

- ( id )init
{
    if( ( self = [ self initWithNibName: @"DMFileSystemFileListTableView" bundle: nil ] ) )
    {}
    
    return self;
}

- ( id )initWithPath: ( NSString * )path
{
    if( ( self = [ self initWithFile: [ DMFile fileWithPath: path ] ] ) )
    {}
    
    return self;
}

- ( id )initWithFile: ( DMFile * )file
{
    if( file == nil || file.isReadable == NO || ( file.isDirectory == NO && file.targetFile.isDirectory == NO ) )
    {
        return nil;
    }
    
    if( ( self = [ self init ] ) )
    {
        _file = [ file retain ];
    }
    
    return self;
}

- ( void )dealloc
{
    [ _file     release ];
    [ _files    release ];
    
    [ super dealloc ];
}

- ( void )viewDidUnload
{
    [ _file     release ];
    [ _files    release ];
    
    [ super viewDidUnload ];
}

- ( void )viewDidLoad
{
    DMFile  * file;
    NSString * path;
    NSArray  * files;
    
    [ super viewDidLoad ];
    
    self.navigationItem.title = _file.displayName;
    
    _files     = [ [ NSMutableArray alloc ] initWithCapacity: 256 ];
    
    files = [ [ NSFileManager defaultManager ] contentsOfDirectoryAtPath: _file.path error: NULL ];
    
    for( path in files )
    {
        path = [ _file.path stringByAppendingPathComponent: path ];
        file = [ DMFile fileWithPath: path ];
        
        if( file != nil )
        {
            [ _files addObject: file ];
        }
        else
        {
            [ _files addObject: path ];
        }
    }
}

- ( void )viewWillAppear: ( BOOL )animated
{
    NSString         * path;
    DMFile           * file;
    UIViewController * controller;
    
    [ super viewWillAppear: animated ];
    
    if( animated == NO )
    {
        path = [ [ DMPreferences sharedInstance ] activePath ];
        
        if( path.length > 0 )
        {
            for( file in _files )
            {
                if( [ file isKindOfClass: [ DMFile class ] ] && [ path hasPrefix: file.path ] )
                {
                    controller = [ [ DMFileSystemFileListTableViewController alloc ] initWithFile: file ];
                    
                    if( controller != nil )
                    {
                        [ self.navigationController pushViewController: controller animated: NO ];
                    }
                    
                    [ controller release ];
                }
            }
        }
    }
    else
    {
        [ [ DMPreferences sharedInstance ] setActivePath: _file.path ];
    }
}

- ( void )viewDidAppear: ( BOOL )animated
{
    UILabel         * label;
    UIBarButtonItem * item;
    UIBarButtonItem * spacer;
    
    [ super viewDidAppear: animated ];
    
    spacer = [ [ UIBarButtonItem alloc ] initWithBarButtonSystemItem: UIBarButtonSystemItemFlexibleSpace target: nil action: NULL ];
    
    label                   = [ [ UILabel alloc ] initWithFrame: CGRectMake( 0, 0, self.navigationController.toolbar.bounds.size.width - 50, self.navigationController.toolbar.bounds.size.height ) ];
    label.backgroundColor   = [ UIColor clearColor ];
    label.textColor         = [ UIColor whiteColor ];
    label.font              = [ UIFont systemFontOfSize: [ UIFont smallSystemFontSize ] ];
    label.textAlignment     = UITextAlignmentCenter;
    label.lineBreakMode     = UILineBreakModeMiddleTruncation;
    label.autoresizingMask  = UIViewAutoresizingFlexibleWidth
                            | UIViewAutoresizingFlexibleHeight
                            | UIViewAutoresizingFlexibleLeftMargin
                            | UIViewAutoresizingFlexibleTopMargin
                            | UIViewAutoresizingFlexibleRightMargin
                            | UIViewAutoresizingFlexibleBottomMargin;
    
    if( [ [ UIDevice currentDevice ] userInterfaceIdiom ] == UIUserInterfaceIdiomPad )
    {
        label.textColor = [ UIColor colorWithRed: ( CGFloat )0.44 green: ( CGFloat )0.47 blue: ( CGFloat )0.5 alpha: ( CGFloat )1 ];
    }
    
    [ label setText: _file.path ];
    
    item                                    = [ [ UIBarButtonItem alloc ] initWithCustomView: label ];
    self.navigationController.toolbar.items = [ NSArray arrayWithObjects: spacer, item, spacer, nil ];
    
    [ spacer release ];
    [ item   release ];
    [ label  release ];
}

- ( BOOL )shouldAutorotateToInterfaceOrientation: ( UIInterfaceOrientation )orientation
{
    ( void )orientation;
    
    return YES;
}

@end
