/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina - www.xs-labs.com
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

/*!
 * @file        ...
 * @copyright   (c) 2012 - Jean-David Gadina - www.xs-labs.com
 * @abstract    ...
 */

#import "DMFileSystemFileListTableViewController+UITableViewDataSource.h"
#import "DMFileSystemFileListTableViewCell.h"
#import "DMFile.h"

@implementation DMFileSystemFileListTableViewController( UITableViewDataSource )

- ( NSInteger )numberOfSectionsInTableView: ( UITableView * )tableView
{
    ( void )tableView;
    
    return 1;
}

- ( NSInteger )tableView: ( UITableView * )tableView numberOfRowsInSection: ( NSInteger )section
{
    ( void )tableView;
    ( void )section;
    
    return ( NSInteger )_files.count;
}

- ( UITableViewCell * )tableView: ( UITableView * )tableView cellForRowAtIndexPath: ( NSIndexPath * )indexPath
{
    id                                  object;
    DMFileSystemFileListTableViewCell * cell;
    
    cell = ( DMFileSystemFileListTableViewCell * )[ tableView dequeueReusableCellWithIdentifier: DMFileSystemFileListTableViewCellID ];
    
    if( cell == nil || [ cell isKindOfClass: [ DMFileSystemFileListTableViewCell class ] ] == NO )
    {
        cell = [ [ DMFileSystemFileListTableViewCell new ] autorelease ];
    }
    
    @try
    {
        object = [ _files objectAtIndex: ( NSUInteger )( indexPath.row ) ];
        
        if( [ object isKindOfClass: [ DMFile class ] ] )
        {
            cell.file = object;
        }
        else if( [ object isKindOfClass: [ NSString class ] ] )
        {
            cell.file               = nil;
            cell.textLabel.text     = [ [ NSFileManager defaultManager ] displayNameAtPath: object ];
            cell.imageView.image    = [ UIImage imageNamed: @"Protected.png" ];
        }
    }
    @catch ( NSException * e )
    {
        ( void )e;
        
        cell.file = nil;
    }
    
    cell.alternateBackground = ( indexPath.row % 2 ) ? YES : NO;
    
    return cell;
}

@end
