/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina - www.xs-labs.com
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

/*!
 * @file        ...
 * @copyright   (c) 2012 - Jean-David Gadina - www.xs-labs.com
 * @abstract    ...
 */

#import "DMFileSystemTextViewController.h"
#import "DMFileSystemTextViewController+Private.h"
#import "DMFile.h"
#import "DMHUDView.h"

@implementation DMFileSystemTextViewController

@synthesize textView = _textView;

- ( id )initWithFile: ( DMFile * )file
{
    if( ( self = [ self initWithNibName: @"DMFileSystemTextView" bundle: nil ] ) )
    {
        _file = [ file retain ];
    }
    
    return self;
}

- ( void )dealloc
{
    [ _file     release ];
    [ _textView release ];
    [ _hud      release ];
    
    _textView = nil;
    
    [ super dealloc ];
}

- ( void )viewDidUnload
{
    [ _file     release ];
    [ _textView release ];
    [ _hud      release ];
    
    [ super viewDidUnload ];
}

- ( void )viewDidLoad
{
    [ super viewDidLoad ];
    
    self.navigationItem.title = _file.displayName;
    _textView.text            = @"";
    _textView.font            = [ UIFont fontWithName: @"Courier" size: [ UIFont smallSystemFontSize ] ];
    
    _hud        = [ DMHUDView new ];
    _hud.center = self.view.center;
    
    if( _file.size > 0 )
    {
        [ self.view addSubview: _hud ];
    }
}

- ( void )viewDidAppear: ( BOOL )animated
{
    UIBarButtonItem    * spacer;
    UIBarButtonItem    * item;
    UIBarButtonItem    * infos;
    UIBarButtonItem    * openIn;
    UISegmentedControl * segment;
    
    [ super viewDidAppear: animated ];
    
    spacer = [ [ UIBarButtonItem alloc ] initWithBarButtonSystemItem: UIBarButtonSystemItemFlexibleSpace target: nil action: NULL ];
    
    segment                       = [ [ UISegmentedControl alloc ] initWithItems: [ NSArray arrayWithObjects: NSLocalizedString( @"ASCII", @"ASCII" ), NSLocalizedString( @"Hex", @"Hex" ), nil ] ];
    segment.segmentedControlStyle = UISegmentedControlStyleBar;
    segment.selectedSegmentIndex  = ( _hasHex == YES ) ? 1 : 0;
    
    [ segment addTarget: self action: @selector( toggleDisplay: ) forControlEvents: UIControlEventValueChanged ];
    
    if( _hasText == NO && _hasHex == NO && _file.size > 0 )
    {
        [ NSThread detachNewThreadSelector: @selector( loadText: ) toTarget: self withObject: segment ];
    }
    
    item                                    = [ [ UIBarButtonItem alloc ] initWithCustomView: segment ];
    infos                                   = [ [ UIBarButtonItem alloc ] initWithBarButtonSystemItem: UIBarButtonSystemItemSearch target: self action: @selector( showInfos: ) ];
    openIn                                  = [ [ UIBarButtonItem alloc ] initWithBarButtonSystemItem: UIBarButtonSystemItemAction target: self action: @selector( openIn: ) ];
    
    if( _file.size > 0 )
    {
        self.navigationController.toolbar.items = [ NSArray arrayWithObjects: infos, spacer, item, spacer, openIn, nil ];
    }
    else
    {
        self.navigationController.toolbar.items = [ NSArray arrayWithObjects: infos, spacer, openIn, nil ];
    }
    
    [ spacer    release ];
    [ item      release ];
    [ segment   release ];
    [ infos     release ];
    [ openIn    release ];
}

- ( BOOL )shouldAutorotateToInterfaceOrientation: ( UIInterfaceOrientation )orientation
{
    ( void )orientation;
    
    return YES;
}

@end
