/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina - www.xs-labs.com
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

/*!
 * @file        ...
 * @copyright   (c) 2012 - Jean-David Gadina - www.xs-labs.com
 * @abstract    ...
 */

#import "DMMasterViewController+UITableViewDataSource.h"
#import "DMMasterTableViewCell.h"
#import "DMGroupedTableViewCellBackgroundView.h"

@implementation DMMasterViewController( UITableViewDataSource )

- ( NSInteger )numberOfSectionsInTableView: ( UITableView * )tableView
{
    ( void )tableView;
    
    return 1;
}

- ( NSInteger )tableView: ( UITableView * )tableView numberOfRowsInSection: ( NSInteger )section
{
    ( void )tableView;
    
    if( section == 0 )
    {
        return 7;
    }
    
    return 0;
}

- ( UITableViewCell * )tableView: ( UITableView * )tableView cellForRowAtIndexPath: ( NSIndexPath * )indexPath
{
    UITableViewCell                      * cell;
    DMGroupedTableViewCellBackgroundView * backgroundView;
    
    cell = [ tableView dequeueReusableCellWithIdentifier: DMMasterTableViewCellID ];
    
    if( cell == nil )
    {
        cell = [ [ DMMasterTableViewCell new ] autorelease ];
    }
    
    if( indexPath.section == 0 )
    {
        switch( indexPath.row )
        {
            case 0:
                
                cell.imageView.image = [ UIImage imageNamed: @"MainMenu-DeviceInfos.png" ];
                cell.textLabel.text  = NSLocalizedString( @"MainMenu-DeviceInfos", @"MainMenu-DeviceInfos" );
                break;
                
            case 1:
                
                cell.imageView.image = [ UIImage imageNamed: @"MainMenu-Usage.png" ];
                cell.textLabel.text  = NSLocalizedString( @"MainMenu-Usage", @"MainMenu-Usage" );
                break;
                
            case 2:
                
                cell.imageView.image = [ UIImage imageNamed: @"MainMenu-Processes.png" ];
                cell.textLabel.text  = NSLocalizedString( @"MainMenu-Processes", @"MainMenu-Processes" );
                break;
                
            case 3:
                
                cell.imageView.image = [ UIImage imageNamed: @"MainMenu-Network.png" ];
                cell.textLabel.text  = NSLocalizedString( @"MainMenu-Network", @"MainMenu-Network" );
                break;
                
            case 4:
                
                cell.imageView.image = [ UIImage imageNamed: @"MainMenu-Logs.png" ];
                cell.textLabel.text  = NSLocalizedString( @"MainMenu-Logs", @"MainMenu-Logs" );
                break;
                
            case 5:
                
                cell.imageView.image = [ UIImage imageNamed: @"MainMenu-FileSystem.png" ];
                cell.textLabel.text  = NSLocalizedString( @"MainMenu-FileSystem", @"MainMenu-FileSystem" );
                break;
                
            case 6:
                
                cell.imageView.image = [ UIImage imageNamed: @"MainMenu-Battery.png" ];
                cell.textLabel.text  = NSLocalizedString( @"MainMenu-Battery", @"MainMenu-Battery" );
                break;
                
            default:
                
                break;
        }
        
        backgroundView                      = [ [ [ DMGroupedTableViewCellBackgroundView alloc ] initWithFrame: CGRectZero ] autorelease ];
        backgroundView.backgroundViewType   = DMGroupedTableViewCellBackgroundViewTypeMiddle;
        backgroundView.fillColor            = [ UIColor colorWithPatternImage: [ UIImage imageNamed: @"RootTable-CellBackground.png" ] ];
        cell.textLabel.backgroundColor      = [ UIColor clearColor ];
        
        if( indexPath.row == 0 )
        {
            backgroundView.backgroundViewType = DMGroupedTableViewCellBackgroundViewTypeTop;
        }
        else if( indexPath.row == 6 )
        {
            backgroundView.backgroundViewType = DMGroupedTableViewCellBackgroundViewTypeBottom;
        }
        else
        {
            backgroundView.backgroundViewType = DMGroupedTableViewCellBackgroundViewTypeMiddle;
        }
        
        cell.backgroundView = backgroundView;
    }
    
    return cell;
}

@end
